// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

Css.$$global("html", /* :: */[
      Css.height(Css.pct(100)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* [] */0
      ]
    ]);

Css.$$global("body", /* :: */[
      Css.height(Css.pct(100)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* :: */[
          Css.display(Css.flexBox),
          /* :: */[
            Css.alignItems(Css.center),
            /* :: */[
              Css.justifyContent(Css.center),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var app = Css.style(/* :: */[
      Css.background(Css.red),
      /* :: */[
        Css.color(Css.white),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* app */app];

var component = ReasonReact.statelessComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: app
                        }, "Pokedex");
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/*  Not a pure module */
