// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Enzyme = require("enzyme");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$Repokedex = require("./App.bs.js");

describe("App component", (function () {
        return Jest.test("renders", (function () {
                      var component = Enzyme.shallow(ReasonReact.element(/* None */0, /* None */0, App$Repokedex.make(/* array */[])));
                      return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](component));
                    }));
      }));

/*  Not a pure module */
